### ISSUE TITLE
Umm... did you read the code?

### ISSUE THREAD

**Issue by MineRobber9000** [pakoito/MarI-O#2]
Specifically, the part that says:
```lua
-- Feel free to use this code, but please do not redistribute it.
```

**Comment by borromeotlhs** [comment]
he isn't.  Forking on github isn't a redistribution.

**Comment by michaelpittino** [comment]
He didn't fork it but redistributed it from the pastebin provided in the yt link, which is not allowed.

**Comment by MineRobber9000** [comment]
@borromeotlhs the original isn't on GitHub. it's not a fork.

**Comment by borromeotlhs** [comment]
SO please explain your legal analysis of distribution?  At best, I would think this is having github host it?

**Comment by michaelpittino** [comment]
It's quit simple.
The original author stated he doesn't want it to be redistributed.
The author of this github repo redistributed it (probably without the consent of the original author) which violates copyright.

**Comment by borromeotlhs** [comment]
Errrr.  So does the author think this is redistribution?  If he does, he can and should file a DMCA.  I am NOT a lawyer, so I simply point out that it would DEFINITELY be a distribution (again: my opinion), if anyone downloaded it.  

Heck, depending on the license in this code, actually viewing the code (which I purposely don't), could sign away your rights to even thinking about coding for the rest of your life, I suppose.  

My concern is that I wouldn't utilize or view this code, at all, if I were unsure of the provenance.  This is why I bother asking, and I don't care to defend the creator of this repo.  I just don't care.  

However, I am very much interested in legal analysis :)  @michaelpittino : are you a lawyer?

**Comment by michaelpittino** [comment]
Why suddenly so offensive @borromeotlhs?
Maybe the original author doesn't even bother if someone publishes it here, who knows.
But everyone in the open source community should respect the wishes of an author by not violating the code's license.
I am however, not a lawyer, and never said to be one.

**Comment by borromeotlhs** [comment]
Cool.  Distribution is a legal term.  Can we close this issue now?
